### ISSUE TITLE
Completions not working for Python 3 -- Nvim 0.6.0

### ISSUE THREAD

**Issue by philipGaudreau** [Shougo/ddc-nvim-lsp#29]
# Problems summary
Getting error when trying to get completions from `nvim-lsp` (getting the same from `omni` completion source).
`[denops]     at async Session.handleNotification (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:130:7)`

## Expected
Get completions.

## Environment Information

- ddc.vim version (SHA1): `83047c7`

- denops.vim version (SHA1): `228d4461`

- deno version(`deno -V` output): deno 1.15.3

- OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-71-generic x86_64)

- neovim/Vim `:version` output: 
```
NVIM v0.6.0-dev+550-g29cec32f4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az139-640

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```
<details><summary><code>:checkhealth</code></summary>

```
denops: health#denops#check
========================================================================
  - INFO: Supported Deno version: `1.14.0`
  - INFO: Detected Deno version: `1.15.3`
  - OK: Deno version check: passed
  - INFO: Supported Neovim version: `0.5.0`
  - INFO: Detected Neovim version: `0.6.0`
  - OK: Neovim version check: passed
  - INFO: Denops status: `running`
  - OK: Denops status check: passed

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: pyright: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/0'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.0.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - ...
  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: tmux

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/philip/miniconda3/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "~/miniconda3/envs/neovim/bin/python"
  - INFO: Executable: /home/philip/miniconda3/envs/neovim/bin/python
  - INFO: Python version: 3.9.7
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v17.0.1
  - INFO: Nvim node.js host: /home/philip/.local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

sniprun: health#sniprun#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 , sniprun will try to make good use of that
  - OK: Rust toolchain found
  - OK: sniprun binary found
  - OK: sniprun binary runs correctly

targets: health#targets#check
========================================================================
  - WARNING: Conflicting mapping found:
    a| → :<C-U>normal! F|vf|<CR>
    | → {'separator': [{'d': '|'}]}
  - WARNING: Conflicting mapping found:
    i| → :<C-U>normal! T|vt|<CR>
    | → {'separator': [{'d': '|'}]}

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/philip/.cache/nvim/lsp.log
  - INFO: Log size: 1046 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for python: ABI version 13
...
```
</details>

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
call ddc#custom#patch_global('sources', ['nvim-lsp'])
call ddc#custom#patch_global('sourceOptions', {
      \ '_': { 'matchers': ['matcher_head'] },
      \ 'nvim-lsp': {
      \   'mark': 'lsp',
      \   'forceCompletionPattern': '\.\w*|:\w*|->\w*' },
      \ })
call ddc#custom#patch_global('sourceParams', {
      \ 'nvim-lsp': { 'kindLabels': { 'Class': 'c' } },
      \ })
call ddc#enable()

lua << EOF
vim.lsp.handlers["textDocument/publishDiagnostics"] =
    vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
        underline = true,
        signs = true,
        update_in_insert = true
    })

local nvim_lsp = require('lspconfig')
nvim_lsp["pyright"].setup{}
EOF
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. Open a python file.
2. Start typing (ex.: `def`)

## Screenshot (if possible)
![Screen Shot 2021-11-12 at 12 01 32](https://user-images.githubusercontent.com/22773951/141506040-7eb24843-a002-419d-ae30-2e8524a85061.png)

The error is `[denops]     at async Session.handleNotification (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:130:7)`

**Comment by Shougo** [comment]
It works for me.

Your neovim and deno are not latest.  Please update it.
`nvim-lspconfig` must be the latest.

> The error is [denops] at async Session.handleNotification (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:130:7)

Why don't you execute `:mes` to print full messages?

And you have not uploaded real minimal vimrc.
Note:  The statusline is customed in your screenshot.

My vimrc is:

```vim
if &compatible
  set nocompatible
endif

set runtimepath^=~/work/ddc.vim
set runtimepath^=~/work/denops.vim
set runtimepath^=~/work/ddc-matcher_head
set runtimepath^=~/work/ddc-sorter_rank
set runtimepath^=~/work/ddc-around

if has('nvim')
  set runtimepath+=~/src/nvim-lspconfig
  set runtimepath^=~/work/ddc-nvim-lsp

  lua << EOF
vim.lsp.handlers["textDocument/publishDiagnostics"] =
    vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
        underline = true,
        signs = true,
        update_in_insert = true
    })
require'lspconfig'.pyright.setup{}
EOF
endif

set completeopt=menuone,noinsert

filetype plugin indent on
syntax enable

call ddc#custom#patch_global('sources', ['nvim-lsp'])
call ddc#custom#patch_global('sourceOptions', {
      \ '_': { 'matchers': ['matcher_head'] },
      \ 'nvim-lsp': {
      \   'mark': 'lsp',
      \   'forceCompletionPattern': '\.\w*|:\w*|->\w*' },
      \ })
call ddc#custom#patch_global('sourceParams', {
      \ 'nvim-lsp': { 'kindLabels': { 'Class': 'c' } },
      \ })
call ddc#enable()
```

Closing.

**Comment by Shougo** [comment]
![スクリーンショット_2021-11-13_08-31-26](https://user-images.githubusercontent.com/41495/141595246-1e0c5604-d006-4a60-ba3a-904a690cb9a3.png)

**Comment by Shougo** [comment]
The minimal vimrc does not means your ddc configuration part.
It must be executed by `nvim -u minimal.vimrc`.

We have not ESP skills.

**Comment by philipGaudreau** [comment]
Hi!

I was not aware of the `:mes` command, very helpful, thank you!

As for the complete error, there it is:

```
[denops] Error: Failed to call 'onEvent' with ["InsertEnter"]: TypeError: error sending request for url (https://x.nest.land/arithmetic4@0.1.1/mod.ts): error trying to connect: invalid certificate: UnknownIssuer
[denops]     at https://deno.land/x/fonction@v1.8.0-beta.7/deps.ts:8:8
[denops]     at async Ddc.autoload (file:///home/philip/.local/share/nvim/site/pack/packer/start/ddc.vim/denops/ddc/ddc.ts:195:11)
[denops]     at async Ddc.checkInvalid (file:///home/philip/.local/share/nvim/site/pack/packer/start/ddc.vim/denops/ddc/ddc.ts:226:5)
[denops]     at async Ddc.onEvent (file:///home/philip/.local/share/nvim/site/pack/packer/start/ddc.vim/denops/ddc/ddc.ts:280:5)
[denops]     at async Session.onEvent (file:///home/philip/.local/share/nvim/site/pack/packer/start/ddc.vim/denops/ddc/app.ts:111:7)
[denops]     at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:99:12)
[denops]     at async https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:108:18
[denops]     at async Session.handleRequest (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:104:29)
[denops]     at Session.call (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:207:13)
[denops]     at async Service.dispatch (file:///home/philip/.local/share/nvim/site/pack/packer/start/denops.vim/denops/@denops-private/service.ts:101:14)
[denops]     at async Session.invoke (file:///home/philip/.local/share/nvim/site/pack/packer/start/denops.vim/denops/@denops-private/host/nvim.ts:48:16)
[denops]     at async Session.dispatch (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:99:12)
[denops]     at async Session.handleNotification (https://deno.land/x/msgpack_rpc@v3.1.4/session.ts:130:7)
```
It was produced with your minimal `vimrc` (I updated `nvim` and `deno` to latest).

**Comment by philipGaudreau** [comment]
I checked about the error, and it says it might be because of a proxy issue, but I can use DDC correctly with other sources like `treesitter` or `around`.

Also, if I execute `deno run https://deno.land/std/examples/welcome.ts`, I get:
```
Download https://deno.land/std/examples/welcome.ts
Warning Implicitly using latest version (0.114.0) for https://deno.land/std/examples/welcome.ts
Download https://deno.land/std@0.114.0/examples/welcome.ts
Check https://deno.land/std/examples/welcome.ts
Welcome to Deno!
```

Output of `deno --version`: 
```
deno --version
deno 1.16.1 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by Shougo** [comment]
It seems the server certificate problem.
So it is not ddc or ddc-nvim-lsp problem.
I cannot fix the problem.  I have not ESP skills.

**Comment by Shougo** [comment]
It works for me.

```typescript
import {
  add,
} from 'https://x.nest.land/arithmetic4@0.1.1/mod.ts'

console.log(add(1, 2));
```

**Comment by Shougo** [comment]
>I checked about the error, and it says it might be because of a proxy server issue, but I can use DDC correctly with other sources like treesitter or around.

Yes, because ddc-nvim-lsp source only uses `equal` module.
Please see the dependency list.

`equal` -> `fonction` -> `equal`

**Comment by Shougo** [comment]
And why I use `equal` module instead.  Please read this.

https://github.com/Shougo/ddc-nvim-lsp/pull/13

**Comment by Shougo** [comment]
I have removed `equal` module.  Please update to the latest.
